// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $posts_type_slug_ from "./routes/posts/[type]/[slug].tsx";
import * as $posts_type_index from "./routes/posts/[type]/index.tsx";
import * as $products_product_ from "./routes/products/[product].tsx";
import * as $resources_index from "./routes/resources/index.tsx";
import * as $AddToCart from "./islands/AddToCart.tsx";
import * as $BuyNow from "./islands/BuyNow.tsx";
import * as $Cart from "./islands/Cart.tsx";
import * as $DownloadBtn from "./islands/DownloadBtn.tsx";
import * as $ProductDetails from "./islands/ProductDetails.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/posts/[type]/[slug].tsx": $posts_type_slug_,
    "./routes/posts/[type]/index.tsx": $posts_type_index,
    "./routes/products/[product].tsx": $products_product_,
    "./routes/resources/index.tsx": $resources_index,
  },
  islands: {
    "./islands/AddToCart.tsx": $AddToCart,
    "./islands/BuyNow.tsx": $BuyNow,
    "./islands/Cart.tsx": $Cart,
    "./islands/DownloadBtn.tsx": $DownloadBtn,
    "./islands/ProductDetails.tsx": $ProductDetails,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
